opencryptoki/libica

src/tests/suite.run

Put some separators to the test cases outputs so suite.out
is more readable.

make suite.out user-friendly

---

src/tests/suite.run

Currently for tests that set an environment variable we get errors like the following:
```
Running 'ICAPATH=1 libica_ecdh_test ' ...
./suite.run: line 30: ./ICAPATH=1: No such file or directory
... done
```
Fix this by calling the tests with "bash -c" and including the current directory into the PATH variable.
Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>

Fix tests with environment variables

---

src/icastats.c
src/icastats_shared.c
src/include/icastats.h
test/icastats_test.c

icastats counters displayed negative numbers for counts
higher than 31 bits in size. Now using 64-bit unsigned values.

Fix icastats counter format

---

src/ica_api.c

Although a DES key has only 56 effective bits, all 64 bits must be
considered, because the parity bits are spread over all 8 bytes of
the key.

Fix DES and TDES key length.

---

src/include/s390_cbccs.h

This fix is introduced to satisfy FIPS tests. They require the
output iv to be the iv resulting from decrypting the last block
with a zero iv as input. But note that this is not described
in the NIST standard for CBC-CS. According to the standard,
the output iv is simply undefined.

FIPS: provide output iv as required by FIPS tests

---

include/ica_api.h
src/Makefile.am
src/fips.c
src/include/fips.h
test/fips_test.c

When in FIPS mode, perform an integrity check on libica.so by calculating
an HMAC from the file contents using a static HMAC key, and comparing it
to a pre-calculated HMAC in a separate file. The HMAC key and HMAC file
may be provided by a Distributor when building the packet. The test
succeeds if the HMAC file is not present.

FIPS: introduce HMAC based library integrity check

---

src/fips.c

Initialize path variable with nulls by using calloc instead of
malloc, improve checking of hmac length, and rename variables
to more self-explaining names.

FIPS: HMAC based library integrity check addon

---

ChangeLog
configure.ac
libica.spec
src/Makefile.am

- [FEATURE] FIPS: Add HMAC based library integrity check

New libica version 3.7.0

---

src/fips.c

Fixes: https://github.com/opencryptoki/libica/issues/45
Signed-off-by: Dan Horák <dan@danny.cz>

fix library filename for FIPS integrity check

---

test/Makefile.am
test/ec_keygen1_test.sh
test/ec_keygen2_test.sh
test/ecdh1_test.sh
test/ecdh2_test.sh
test/ecdsa1_test.sh
test/ecdsa2_test.sh
test/icastats_test.sh

Only a small helper to aid in test failure debugging.  Can be reverted at any
time.
Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

Make tests more verbose

---

src/fips.c

FIPS: skip SHA3 tests if running on hardware without SHA3

---

src/fips.c

Fixes: 231bba3b32bd ("FIPS: introduce HMAC based library integrity check")
Fixes: f9f148487fad ("fix library filename for FIPS integrity check")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>

FIPS: use full library version for hmac filename.

---

Makefile.am
doc/icastats.1
src/Makefile.am
src/fips.c
src/icainfo.c
src/include/icastats.h
src/s390_ecc.c

When in FIPS mode, the .hmac file is now created during make and its existence
is enforced by changing the check in routine FIPSCHECK_verify to fail if it
cannot be opened.
This should make it easier for distributors to adapt the lib integrity check for their
distros, just by changing the static hmac key in fips.c and Makefile.am.
Notes:
- The openssl commandline expects a hex key
- The "check: all" in Makefile.am is necessary to create the .hmac file before running the internal tests when doing a "make check" without a "make all" before
- explicitly removing the .hmac file from src/.libs during "make uninstall" is not necessary, as the whole .libs directory is removed

FIPS: enforce the hmac check

---

configure.ac

The openssl binary is needed for FIPS build to compute the HMAC.  Since the
computation of the HMAC calls openssl inside a piped command, a missing
openssl binary will not even produce a build error.  Instead, the HMAC file
will be empty and the library will not load in FIPS mode.
Instead of build error, lets make this a configure error and check during
configuration that the binary "openssl" is available.
Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

FIPS BUILD: check for openssl app

---

src/s390_sha.c

The U64() macro has been removed from OpenSSL 3.0, use a C99 standard
macro instead.
This fixes one part of https://bugzilla.redhat.com/show_bug.cgi?id=1952946

use C99 macro for 64-bit integral type

---

configure.ac

Currently passing eg. --disable-debug actually enables the debug build
as one would expect from --enable-debug. The fix is to omit setting the
enable_foo variable as the "action-if-given" parameter of AC_ARG_ENABLE,
because it handles both the --enable and --disable forms.
Signed-off-by: Dan Horák <dan@danny.cz>

fix handling of --disable-foo options

---

test/Makefile.am
test/icastats_test.c.in

icastats_test used a system installed icastats instead of the build-tree
icastats.  So we actually did not test the icastats binary but still tested
the correct counting.  Use the icastats binary from the build-tree to also
test that binary.
Signed-off-by: Juergen Christ <jchrist@linux.ibm.com>

[TEST] Use build-tree icastats in icastats_test

---

include/ica_api.h
src/ica_api.c
src/include/s390_ecc.h
src/s390_ecc.c
test/ec_keygen_test.c
test/ecdh_test.c
test/ecdsa_test.c
test/testcase.h

This pr provides several fixes for EC support in libica and addresses opencryptoki issue #404: Libica must check at key generate/init/derive if the EC curve is supported. It also adds openssl based EC key checking to prevent against initializing with invalid/corrupted EC key parts. Libica EC tests are adapted to the newly introduced rcs to skip tests if curves are not supported.

Misc ECC fixes

---

src/fips.c

`OPENSSL_hexstr2buf()` allocates the output buffer using `OPENSSL_malloc()`
and it means the buffer must be freed with `OPENSSL_free()`. Usually it's
not a problem, but an application can pass its own malloc/free
implementation to OpenSSL and the allocation/de-allocation functions must
match.
With ibmca engine installed and configured we have experienced a crash
in DNS related tools (`host`, `dig`, ...) in RHEL, because they provide
their own malloc/free.
````
[root@ibm-z-110 ~]# gdb /usr/bin/host
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-15.el8
(gdb) set args localhost
(gdb) run
Starting program: /usr/bin/host localhost
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x3fffc67f910 (LWP 65794)]
[New Thread …
```

buffer must be freed with OPENSSL_free()

---

test/Makefile.am
test/get_functionlist_cex_test.c

This test checks the functionlist of the libica-cex module. All CPACF-related functions and software fallbacks are disabled here, so the mech mode flags must all be zero for these.

TESTCASES: add test for libica-cex

---

test/eddsa_test.c

EVP_DigestVerify was called without a EVP_DigestVerifyInit.
This bug shows up when using openssl 3.0.
This fix solves issue https://github.com/opencryptoki/libica/issues/61

TESTCASES: EVP_DigestVerifyInit was not called in eddsa_test

---

src/ica_api.c

When the qinv value has a leading 0, the padding
of this value in the ica_rsa_key_crt_t struct was
not currectly done in the ica_rsa_crt_key_check()
function. Fixed and tested, and works fine now.
Please note, for newer Openssl there is a simpler way to have the right padding:
BN_bn2binpad(bn_invq, tmp_buf, rsa_key->key_length/2);h

libica: fix wrong padding in rsa_crt_check function

---

include/ica_api.h
src/ica_api.c

CEX adapters support RSA up to 4096 bits. Although RSA key generation in libica is done via openssl, and therefore even greater key lengths would be supported, such keys could not be processed on CEX adapters afterwards. With the removal of sw fallbacks this is now a hard restriction.
The check is not so obvious: while the modulus_bit_length parm specifies the desired key length in bits, the public_key.key_length and private_key.key_length specify bytes.

RSA: limit RSA key length to 4096

---

src/ica_api.c

In case of an unsupported curve nid, `privlen_from_nid()` returns -1. The subsequent `calloc()` will fail with a size of -3 (0xfffffffffffffffd).
Also free the already allocated key in case of an error to avoid a memory leak.

EC: Handle unsupported EC curve in ica_ec_key_new()

---

Makefile.am
src/Makefile.am

The HMAC hash was computed from the libica in the build tree, but
the runtime check is run against the installed libica and those 2
files may be different. E.g. if the runtime one has debuginfo stripped
(and placed into a separate file), the hashes are different.
This commit introduces a new make target: fipsinstall, which creates
the HMAC files in the install directory.

Compute HMAC from installed library

---

src/init.c

Usually libica's own library context is freed in the library destructor when the library is unloaded (i.e. during exit handlers).
OpenSSL also performs its own cleanup in exit handlers, and it may happen that OpenSSL cleanup is performed before the library destructors are called. This may cause crashes when libica's library context has already been freed by OpenSSL cleanup, but the library destructor tries to free it a second time. This causes a double free, and very likely a crash.
Register an OpenSSL cleanup handler to clean up the library context before OpenSSL performs its own cleanup.
Similar fix as for Opencryptoki in https://github.com/opencryptoki/opencryptoki/pull/529

OpenSSL 3.0: Cleanup OpenSSL library context during OpenSSL cleanup

---

src/include/s390_prng.h
src/init.c
src/s390_prng.c

When built in non-FIPS mode, s390_prng_init() initializes a global PRNG instance in the library constructor, which must also be freed in the library destructor. Otherwise it leaks 64 bytes (direct leak) plus 240 bytes (indirect leak) when unloading the library.

Fix memory leak at library unload by uninstantiating global prng instance

---

src/s390_ecc.c

According to the description of CCA verb "Digital Signature Verify" (CSNDDSV) in "Secure Key Solution with the Common Cryptographic Architecture Application Programmer's Guide Version 7.1" the signature verify request may also return 12 / 769 for bad signatures, in addition to 4 / 429. Treat both return codes as bad signature indication.

ECC: Signature verify may also return 12 / 769 for bad signatures

---

Makefile.am
doc/Makefile.am
include/Makefile.am
src/Makefile.am
src/fips.c
src/ica_api.c
src/icastats.c
src/icastats_shared.c
src/include/icastats.h
src/include/rng.h
src/init.c
src/rng.c
test/Makefile.am
test/adapter_handle_test.c

This PR contains a set of commits to reduce the number of open file descriptors and a few other cleanups.
The cleanup covers the following:
- Patch 1/7: fix the autotools clean targets. Now all generated files will be removed by these targets
- Patch 2/7: add user support in stats_munmap()
- Patch 3-4/7: increase readability of stats_mmap() and remove redundant code
Openssh has a hard limit of open file descriptors, while initiating/handling a connection. If openssh is using openssl with a configured libica engine, this hard limit to only 6 open file descriptors may hurt. 
Patch 5/7 closes the shm fd right after the mmap(), which is common practice since a very long time. Just for the record: the mapped shm segment can be used, even if the file descriptor has been closed. This change also …

v5: reduce the number of open file descriptors

---

src/fips.c
src/include/s390_ecc.h
src/s390_ecc.c

This series contains fixes for some compile warnings:
- use of uninitialized variable
- discard of const qualifier

compile warning fixes

---

src/init.c

Set openssl3_initialized = 1 before running the FIPS self tests.
Fixes: eee292c07bedb33c55e08bda95b9db9449525d6b

Fix testcases failures in the CI

---

src/ica_api.c

Don't allow Ed/X functions if the libica is build with FIPS enabled and the system runs in FIPS mode.

Fix FIPS checking for Ed/X functions

---

src/s390_ecc.c

The ec_key_check() routine internally uses OpenSSL calls. In case libica is called from an OpenSSL provider, avoid a recursive loop by using libica's own OpenSSL library context with the default or fips provider loaded.

ECC: ec_key_check() uses OpenSSL, thus use own library context

---

test/eddsa_test.c
test/x_test.c

We want the tests to be skipped only when fips mode is active, i.e. kernel, openssl, and libica are in active fips mode.

FIPS 140-3: skip eddsa and x-tests only when in active fips mode

---

src/s390_crypto.c

The AES-GCM mechanisms based on the MSA8 KMA instruction
had no property flags indicating available key lengths.
As all 3 key lengths (128, 192, 256) came with MSA8, no
need to individually check for availability.

bugfix: provide property flags for MSA8 mechanisms

---

test/Makefile.am

Exclude the generated source file for icastats_test. This fixes the distcheck and related build targets by enforcing the re-generation of the source file.
Signed-off-by: Holger Dengler <dengler@linux.ibm.com>
More detailed explanation: the generated source-file for the icastats_test executable contains the absolute path to the icastats binary. This should avoid, that the test executable use another icastats version for the test (e.g. the one from a package install). For the distribution make targets (dist, dictcheck, et. al.) it is important, that the generated source file test/icastats_test.c is excluded from the distribution tarball, so that the source generation is triggered correctly for the rebuild, e.g. for `make distcheck`.
Without this commit, a clean `./bootstrap.sh ; ./configure …

build: exclude generated sources for distribution

---

include/ica_api.h
libica.map
src/ica_api.c
src/include/s390_aes.h

Function ica_aes_xts() does not support multi-part operations (although the parameter description for the tweak parameter indicates that it would support multi-patrt operations, which is not true).
Add a new function ica_aes_xts_ex() that additionally takes the IV as parameter. For the very first part, the tweak must be specified. Internally the initial IV is calculated (via PCC instruction). After a successful operation on the first part, the resulting IV is returned, and must be passed to subsequent calls to ica_aes_xts_ex() to continue the operation.
For intermediate parts, parameter tweak must be NULL. Then, the IV passed as parameter is used for the operation. The IV is updated on return.
The first and intermediate parts must be a multiple on the AES block size. Only the last part …

AES-XTS: Support multi part operations

---

src/icastats_shared.c

A change to the Linux kernel in 4.19 for added security is changing the behavior when opening shared memory segments. The O_CREAT flag must not be used for existing segments.

bugfix: permission denied on shared memory segments

---

test/Makefile.am
test/rsa_test_x.c

Added a new special RSA test:
The idea is to check that leading zeros on the input message or encrypted message or decrypted message are processed correctly. This is more a proof for the kernel and crypto firmware and hardware stack.
Please have in mind, that the kernel has two pathes to resolve RSA requests via ICA interface: CCA and Accelerator. By default all RSA encrypt/decrypts pushed to the kernel via ICA API are forwarded to accelerator cards and thus the CCA code is not passed. Disable all accelerator cards to have the CCA code tested.

New testcase rsa_test_x

---

ChangeLog
configure.ac
libica.spec
src/Makefile.am

[UPDATE] syslog msgs only in error cases
[UPDATE] don't count statistics in fips power-on self tests 
[PATCH] various fixes and some new tests

New libica version 4.2.2

---

src/icastats.c
src/icastats_shared.c
src/include/icastats.h

The '--summary' option of icastats did not display correct statistics since the introduction of per key keysize counters with libica version 4.0.0.
To display the correct summary counters, the all-key-size-counter values of an algorithm that supports multiple key sizes must be calculated like it is done in get_stats_data(). Adjust get_stats_data() function and friends so that it now also can be called from get_stats_sum() and can optionally operate on a specified statistics segment (i.e. the one where the summary statistics have been calculated in), not just the global one.

icastats: Fix summary option to display correct summary information

---

src/ica_api.c

Replace deprecated ioctl Z90STAT_STATUS_MASK by ZCRYPT_STATUS_MASK 
as this legacy ioctl will be removed soon.

Replace deprecated ioctl

---

src/init.c

Ensure OpenSSL is initialized and the OpenSSL config is loaded BEFORE creating libica's library context. Otherwise the OpenSSL config is loaded later, which may cause that all configured providers (e.g. the IBMCA provider) are also loaded into the library context. When the IBMCA provider is loaded into libica's library context, then a recursion can happen, since the IBMCA provider calls libica itself. Thus, we need to make sure that only the default or fips provider is loaded in the library context.
This change is important for applications that do not itself initialize OpenSSL. If they do, then libica's OpenSSL initialization is a no-op.

Ensure OpenSSL config is loaded before creating libica's own library context

---

test/Makefile.am

The ecdsa_test.h file was missing in the EXTRA_DIST list.

Make: fix make distcheck

---

src/icastats_shared.c

If icastats is used with option '--summary' and it encounters a statistics shared memory segment for a user that no longer exists, it fails with 'get_stats_sum: : Success'. This is because getpwuid() fails, but does not set errno, so that perror prints 'Success'.
Instead of failing, just ignore such shared memory segments for user that do no longer exist. This behavior is consistent with the behavior of 'icastats --all' which shows statistics for all users, and also ignores shared memory segments for user that do no longer exist.

icastats: Ignore unknown user in summary report

---

src/s390_ecc.c

If we are in fips mode, the k-value is created via openssl. This may cause a cc=2 (random number not invertible) from the KDSA instruction. In this case loop over KDSA with new random values. But don't loop over calls to KDSA with unchanged k-value in the non-fips case. This could lead to an endless loop.

ECC: fix KDSA sign behavior

---

src/ica_api.c
src/include/s390_aes.h
src/include/s390_gcm.h

This pull request does some rework on gcm parm checking for the old and new gcm API:
Some length constants were wrong, some checks were wrong, some checks were missing, and there were some typos in comments.

Rework gcm parm checking

---

include/ica_api.h
libica.map
src/ica_api.c

When running in fips mode, the GCM iv is created internally via an approved random source. Applications are not allowed to use an own, external iv. The new API function allows to override this behavior and allow an external GCM iv in fips mode. In this case the application is responsible for creating the iv in a compliant way.

GCM: new API function ica_allow_external_gcm_iv_in_fips_mode

---

src/fips.c
src/include/fips.h
src/init.c

In libica's library constructor OpenSSL is initialized since commit 05c4e36b1208193cd11fbc39347835c5a112c71b "Ensure OpenSSL config is loaded before creating libica's own library context". This will also cause OpenSSL to evaluate the OpenSSL config file and load providers configured there.
Even without this commit, it can happen when libica is in FIPS mode, that OpenSSL gets implicitly initialized by OpenSSL usage within the FIPS power on tests, which run as part of the library constructor.
If OpenSSL has been initialized by the application already, then the attempt to initialize OpenSSL again by libica is a no-operation. However, if the libica constructor is the very first to initialize OpenSSL this can cause problems. For applications that link against libica (via -lica), the libica …

Initialize mechanism list before initializing OpenSSL in icainit

---

test/Makefile.am

OpenSSL supports CEX exploitation since version v3.2.x. Libica and its testcases use OpenSSL as helper and fallback, so disable the CEX acceleration for all tests.
If the environment variable is already set, use it as is without modifying it. In this case, it is up to the user to choose the right settings.
Fixes: Issue #126
Link: https://github.com/opencryptoki/libica/issues/126

test: disable CEX usage in OpenSSL for all tests

---

src/include/s390_crypto.h

The asm keyword is a GNU extension. When writing code that can be compiled with -ansi and the various -std options, use __asm__ instead of asm.

Use __asm__  instead of asm

---

configure.ac
src/fips.c
src/ica_api.c
src/include/s390_aes.h
src/perlasm/s390x.pm
src/s390_crypto.c
src/s390_ecc.c

Configure it via `./configure CC=clang ....` to use clang instead of gcc.

Add support for building libica with clang and a few fixes

---

include/ica_api.h
src/fips.c
src/ica_api.c
src/icainfo.c
src/icastats.c
src/include/fips.h
src/init.c
src/s390_ecc.c
src/s390_rsa.c
test/aes_gcm_kma_test.c
test/cbccs_test.c
test/des_cbc_test.c
test/fips_test.c

Since the last fips 140-3 update in 2022, a few rules are stricter now:
1. ECDSA-verify is no longer allowed for CAVP testing
2. The fips indicator must now be incorporated into the API itself. It's no
more allowed to just give applications the opportunity to check if an API
is approved or not.
3. If an algorithm or API is non-approved, but the library indicates this via
the fips indicator and allows its usage, the API must distinguish these two
cases, e.g. via return codes.

Fips update

---

src/s390_crypto.c

This bug causes an incorrect indication of the availability of algos in fips mode.

Fix bug in condition logic

---

src/s390_crypto.c
test/ec_keygen1_test.sh
test/ec_keygen2_test.sh
test/ecdh1_test.sh
test/ecdh2_test.sh
test/ecdsa1_test.sh
test/ecdsa2_test.sh

Trying to use CCA adapters in an Secure Execution guest fails, because CCA adapters are not usable there. Nevertheless they show up as online, so special checking needs to be added to detect this situation.
Don't set the 'ecc_via_online_card' flag in such case, so that the EC mechanisms are reported to not be available with dynamic hardware when running in an Secure Execution guest, and attempts to use curves that would require a CCA adapter fail with ENODEV. This can then be handled by the calling applications appropriately.

CCA adapters are not usable in an Secure Execution guest

---

ChangeLog
configure.ac
libica.spec
src/Makefile.am

New libica version 4.4.1

---

configure.ac
src/openssl3-fips.cnf.in

The name of the OpenSSL FIPS config file may be different on various distros. It is included in src/openssl3-fips.cnf when used with OpenSSL 3.0 or later.
To use a specific name:
./configure --enable-fips --with-fips-config=fips_local.cnf
The default remains fipsmodule.cnf. It is only used when --enable-fips is also specified, and libica is built against OpenSSL 3.0 or later.

CONFIGURE: Make the OpenSSL FIPS config file name configurable
